env:
  CIRRUS_CLONE_DEPTH: 1

fedora_30_task:
  container:
    image: quay.io/avocado-framework/avocado-vt-ci-fedora-30
  env:
    PYTHON: python3
    AVOCADO_SRC: git+https://github.com/avocado-framework/avocado#egg=avocado_framework
    SETUP: -m pip install .
    VT_TYPE: qemu
  setup_script: &setup_scr
    - $PYTHON --version
    - test -z $AVOCADO_SRC || $PYTHON -m pip install $AVOCADO_SRC
    - $PYTHON $SETUP
  bootstrap_script: &bootstrap_scr
    - $PYTHON -m avocado vt-bootstrap --vt-type=$VT_TYPE --yes-to-all
  list_script: &list_scr
    - $PYTHON -m avocado list --vt-type=$VT_TYPE
  run_script: &dry_run_scr
    - $PYTHON -m avocado --show all run --vt-type=$VT_TYPE --vt-extra-params 'enable_kvm=no' 'nettype=user' 'pre_command_noncritical=yes' -- io-github-autotest-qemu.boot type_specific.io-github-autotest-qemu.migrate.default.tcp.default
